// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7gxHODpNNA1Rxc0s0zZWWBAXdNZ0ODc',
    appId: '1:247194165705:web:eaf6b7282d2a4204c38818',
    messagingSenderId: '247194165705',
    projectId: 'shopinglinemasterung',
    authDomain: 'shopinglinemasterung.firebaseapp.com',
    storageBucket: 'shopinglinemasterung.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpcq3m_3IrkKlhTqe2sswroAmZ7ACtnBc',
    appId: '1:247194165705:android:02538dce67961449c38818',
    messagingSenderId: '247194165705',
    projectId: 'shopinglinemasterung',
    storageBucket: 'shopinglinemasterung.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa4S_RUMI2F1nEaw63qjO0osEW9ANrF1Q',
    appId: '1:247194165705:ios:2e1bfa3316054f5ac38818',
    messagingSenderId: '247194165705',
    projectId: 'shopinglinemasterung',
    storageBucket: 'shopinglinemasterung.firebasestorage.app',
    iosBundleId: 'com.masterung.shoponlinemasterung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa4S_RUMI2F1nEaw63qjO0osEW9ANrF1Q',
    appId: '1:247194165705:ios:2e1bfa3316054f5ac38818',
    messagingSenderId: '247194165705',
    projectId: 'shopinglinemasterung',
    storageBucket: 'shopinglinemasterung.firebasestorage.app',
    iosBundleId: 'com.masterung.shoponlinemasterung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7gxHODpNNA1Rxc0s0zZWWBAXdNZ0ODc',
    appId: '1:247194165705:web:f44ec0b2567284f0c38818',
    messagingSenderId: '247194165705',
    projectId: 'shopinglinemasterung',
    authDomain: 'shopinglinemasterung.firebaseapp.com',
    storageBucket: 'shopinglinemasterung.firebasestorage.app',
  );
}
